version: "3.9"

services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: "big_data_snowflake"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "DogeCoin"
    ports:
      - "30000:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
